### ISSUE TITLE
Will "codec not supported" issue ever be resolved?

### ISSUE THREAD

**Issue by surrounded** [miho/SonoAir#13]
When I want to play something from my Mac through my sonos system via SonoAir and also play it on my computer, or any other airplay speaker for that matter, simultaneously I need to use a program like AirFoil or Porthole and the "codec not supported" issue prevents me from doing this.

Would really love it if this issue could be resolved so I can play to multiple airplay speakers at the same time.

On MacBook Pro running OS X Yosemite 10.10.5 and SonoAir v1.0 (Beta 4.0)

Log output: [Pastebin](http://pastebin.com/kua2nTq4)

**Comment by KarimGeiger** [comment]
I get the following message when trying to play music from my iTunes library on OS X El Capitan:

```
The AirPlay device “Living Room (SonoAir)” is not compatible with this version of iTunes.
```

Also, I cannot select this device as an default output device, which is pretty sad since this would be the main feature for me to use SonoAir. I think this resolves to the same issue described by @surrounded, so I'll just subscribe to this and leave a +1:

+1

**Comment by miho** [comment]
Try [1.0 Beta 6](http://sonoair.mihosoft.eu/).
